//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xkelenton.Models
{
    using ExpressiveAnnotations.Attributes;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Images = new HashSet<Image>();
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter your First Name")]
        [RegularExpression(@"^[A-Za-z]+$", ErrorMessage = "Please include only alphabetic characters")]
        [Display(Name = "Patient Name")]
        public string FirstName { get; set; }


        [Required(ErrorMessage = "Please enter your Last Name")]
        [RegularExpression(@"^[A-Za-z]+$", ErrorMessage = "Please include only alphabetic characters")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        /*        https://learn.microsoft.com/en-us/aspnet/mvc/overview/getting-started/introduction/adding-validation*/
        [Required(ErrorMessage = "Please choose your date of birth")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{{0:dd/MM/yyyy}}", ApplyFormatInEditMode = true)]
        [AssertThat("DateOfBirth < Now()", ErrorMessage = "Please choose a date earlier than today")]
        [Display(Name = "Date Of Birth")]
        public System.DateTime DateOfBirth { get; set; }


        [Required(ErrorMessage = "Please enter your Mobile Number")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Please include a valid 10-digit number")]
        [Display(Name = "Mobile Number")]
        public string MobileNumber { get; set; }
        public string UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
    }
}
