//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xkelenton.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Practitioner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Practitioner()
        {
            this.Appointments = new HashSet<Appointment>();
        }

        [Display(Name = "Practitioner")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter your first fame")]
        [RegularExpression(@"^[A-Za-z]+$", ErrorMessage = "Please include only alphabetic characters")]
        [Display(Name = "Practitioner Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter your last name")]
        [RegularExpression(@"^[A-Za-z]+$", ErrorMessage = "Please include only alphabetic characters")]
        [Display(Name = "Practitioner Last Name")]
        public string LastName { get; set; }


        [Required(ErrorMessage = "Please enter your AHPRA number")]
        [RegularExpression(@"^[A-Za-z]{3}\d{10}$", ErrorMessage = "Please follow the format of starting with three alphabetic characters followed by ten numeric characters ")]
        [Display(Name = "Ahpra Number")]
        public string AhpraNumber { get; set; }

        [Required(ErrorMessage = "Please enter your mobile number")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Please include a valid 10-digit number")]
        [Display(Name = "Mobile Number")]
        public string MobileNumber { get; set; }
        public string UserId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
